format = """
$os\
$username\
$directory\
$git_branch\
$git_status\
$conda\
$docker_context\
$cmd_duration\
\n$character\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "fg:#0E9AA7 bold"
style_root = "fg:#FE8A71 bold"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
disabled = true # Disabled by default
style = "fg:#3DA4AB"

[os.symbols]
Mint = " "

[directory]
style = "fg:#B7C6E7"
format = "[in $path ]($style)"
truncation_length = 3
truncation_symbol = ""

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Github" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[conda]
symbol = " "
style = "fg:#ffd43b"
format = '[ $symbol $environment ]($style)'
ignore_base = false
disabled = false

[docker_context]
symbol = " "
style = "bg:#06969A"
format = '[ $symbol $context ]($style) $path'

[git_branch]
symbol = ' '
style = "fg:#FCA17D"
format = '[ on $symbol$branch ]($style)'

[git_status]
conflicted = "󱠱 "
ahead = "⇡ $count "
behind = "⇣ $count "
untracked = " ×${count} "
stashed = "󱉼 "
modified = " ×${count} "
staged = " ×${count} "
renamed = " ×${count} "
deleted = " ×${count} "
style = "bright-white"
format = "$all_status$ahead_behind"

[cmd_duration]
min_time = 1
show_milliseconds = false
disabled = false
style = "bold italic red"

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[✖](bold red)"
vimcmd_symbol = "[<](bold green)"
